# Random Corp Application Configuration

replicaCount: 2

image:
  repository: docker.io/johnhebeler/randomcorp  # Update with your container registry
  tag: "v2.1.2"
  pullPolicy: Always

service:
  type: LoadBalancer  # Will create Linode NodeBalancer
  port: 80
  targetPort: 8000

frontend:
  image:
    repository: docker.io/johnhebeler/randomcorp-frontend
    tag: "v2.1.2"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

# SQL Server configuration
sqlserver:
  enabled: true
  acceptEula: true
  edition: Developer  # Free for dev/test
  saPassword: "RandomCorp123!"  # Change this!
  persistence:
    enabled: true
    size: 20Gi
    storageClass: linode-block-storage-retain

# Environment variables for API
env:
  - name: SQL_SERVER_HOST
    value: "randomcorp-mssql-linux"
  - name: SQL_SERVER_PORT
    value: "1433"
  - name: SQL_SERVER_DATABASE
    value: "RandomCorpDB"
  - name: SQL_SERVER_USERNAME
    value: "sa"
  - name: SQL_SERVER_PASSWORD
    value: "RandomCorp123!"
  - name: DEBUG
    value: "false"
  - name: LOG_LEVEL
    value: "INFO"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false  # Using LoadBalancer instead
