apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: randomcorp
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-charts/randomcorp
      sourceRef:
        kind: GitRepository
        name: randomcorp-source
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: docker.io/johnhebeler/randomcorp
      tag: "latest"
    frontend:
      image:
        repository: docker.io/johnhebeler/randomcorp-frontend
        tag: "latest"
